services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: moovie
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: